language: scala
scala:
- 2.11.1
env:
- PLAY_VERSION=2.3.0
before_script: 
script:
- sbt test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: lCnIz84gXFW8vU/rCiEmhLQEgaztyy13LGa8Jd2ptLgCHkfvDuok8s8XfkbsZTSRiO8G9hnSv4GDrh6QtVLr7Pf6ig3fCbDkOK+jaAQnjtB5AQJBimZ7/G7Qk1TQeAkcqHS+sd+lwoNxlxwe2IhRYpRv/k8WCGGARvsqa21igBM=
  app: play-angular-require-seed
  on:
    repo: zazrivec/play-angular-require-seed
