language: scala
scala:
- 2.10.4
env:
- PLAY_VERSION=2.2.3
before_script: 
script:
- sbt test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: JxVTgdx189uL5jPxC5ffnQCrA7dN64EeV4iQoOCT02fRHnq3t3tG12buz+PZGFlQKsf/ijXfG10MhbxC/6NqPYjqdDEIt3tboKjZF2uWL3QyCfeRoQOB+6VybHpnwgpj54vqFkjnpWtKAYIGr4gcYwkBHM8hvemstZ2KN3keNRk=
